global:
  postgresql:
    deploy: true
  rabbitmq:
    deploy: true
  redis:
    deploy: true
postgresqlConfig:
  auth:
    admPassword: postgrespostgres
    appPassword: postgresapp
rabbitmqConfig:
  auth:
    password: postgrespostgres
    username: ezdrpadmin
redisConfig:
  auth:
    password: postgrespostgres
